import type { Metadata } from "next";
import Link from "next/link";
import {
  ArrowLeft,
  Cpu,
  Download,
  FileText,
  Gauge,
  Lock,
  Sparkles,
  Terminal,
} from "lucide-react";
import { GitHubIcon } from "@/components/Icons";

const REPO_URL = "https://github.com/bwpx/fpsopti-ai";
const DOWNLOAD_URL =
  "https://github.com/bwpx/fpsopti-ai/releases/latest/download/FPSOptiAI.exe";
const OLLAMA_URL = "https://ollama.com/download";

export const metadata: Metadata = {
  title: "FPSOpti AI — Download & Setup",
  description:
    "Local AI-powered PC performance optimizer for Windows. Scans your hardware and generates per-game graphics settings using a local LLM via Ollama.",
};

export default function FPSOptiAIPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0a] text-[#e4e4e7]">
      {/* Top bar */}
      <div className="border-b border-[#27272a]/70 bg-[#0a0a0a]/80 backdrop-blur-md">
        <div className="max-w-5xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link
            href="/"
            prefetch={false}
            className="inline-flex items-center gap-2 text-sm text-[#a1a1aa] hover:text-amber-400 transition-colors"
          >
            <ArrowLeft size={16} />
            Back to portfolio
          </Link>
          <a
            href="#"
            className="font-mono text-base font-semibold text-[#e4e4e7] hover:text-amber-400 transition-colors"
            aria-label="Top of page"
          >
            <span className="text-amber-500">{"<"}</span>
            mg
            <span className="text-amber-500">{" />"}</span>
          </a>
        </div>
      </div>

      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute -top-32 -right-32 w-[500px] h-[500px] rounded-full bg-amber-500 opacity-[0.06] blur-3xl pointer-events-none" />
        <div className="relative max-w-5xl mx-auto px-6 pt-20 pb-16">
          <p className="text-[11px] font-semibold text-amber-400 uppercase tracking-[0.2em] mb-4 font-mono">
            Desktop App · Windows
          </p>
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold tracking-tight mb-5">
            FPSOpti AI
          </h1>
          <p className="text-lg text-[#a1a1aa] leading-relaxed max-w-[640px] mb-9">
            A local AI-powered PC performance optimizer. Scan your hardware,
            pick a game and target FPS, and get optimized graphics settings
            generated by a small LLM running entirely on your machine.
          </p>

          <div className="flex flex-wrap gap-3 mb-10">
            <a
              href={DOWNLOAD_URL}
              download
              className="inline-flex items-center gap-2 px-5 py-3 bg-amber-600 hover:bg-amber-500 text-white text-sm font-medium rounded-lg transition-all duration-200 hover:shadow-lg hover:shadow-amber-500/20"
            >
              <Download size={16} />
              Download FPSOptiAI.exe
            </a>
            <a
              href={REPO_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-5 py-3 border border-[#27272a] hover:border-amber-500/50 text-[#a1a1aa] hover:text-[#e4e4e7] text-sm font-medium rounded-lg transition-all duration-200"
            >
              <GitHubIcon size={16} />
              View on GitHub
            </a>
            <a
              href="#setup"
              className="inline-flex items-center gap-2 px-5 py-3 text-[#a1a1aa] hover:text-amber-400 text-sm font-medium rounded-lg transition-colors"
            >
              Setup guide ↓
            </a>
          </div>

          <p className="text-xs text-[#52525b] font-mono">
            Windows 10 / 11 · ~ a few hundred MB once Ollama + the model are
            installed
          </p>
        </div>
      </section>

      {/* Features */}
      <section className="border-t border-[#27272a]/70 bg-[#0a0a0a]">
        <div className="max-w-5xl mx-auto px-6 py-16">
          <h2 className="text-2xl font-bold tracking-tight mb-8">
            What it does
          </h2>
          <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
            <FeatureCard
              icon={<Cpu size={20} />}
              title="One-click PC scan"
              body="Auto-detects CPU, RAM, GPU, VRAM, driver version, storage, and display resolution."
            />
            <FeatureCard
              icon={<Sparkles size={20} />}
              title="Local AI report"
              body="Streams a per-setting recommendation from a qwen3:0.6b model running through Ollama."
            />
            <FeatureCard
              icon={<Lock size={20} />}
              title="Fully on-device"
              body="No telemetry, no remote API. Specs and prompts never leave your PC."
            />
            <FeatureCard
              icon={<FileText size={20} />}
              title="Export to .txt"
              body="Save the AI report locally and revisit it any time."
            />
          </div>
        </div>
      </section>

      {/* Setup */}
      <section id="setup" className="border-t border-[#27272a]/70 bg-[#0a0a0a]">
        <div className="max-w-5xl mx-auto px-6 py-16">
          <p className="text-[11px] font-semibold text-amber-400 uppercase tracking-[0.2em] mb-3 font-mono">
            Quick Setup
          </p>
          <h2 className="text-2xl font-bold tracking-tight mb-2">
            How to install
          </h2>
          <p className="text-[#71717a] text-sm mb-10 max-w-[640px]">
            FPSOpti AI uses a model running locally through{" "}
            <a
              href={OLLAMA_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="text-amber-400 hover:text-amber-300 underline-offset-2 hover:underline"
            >
              Ollama
            </a>
            , so the install is three short steps.
          </p>

          <div className="space-y-5">
            <Step
              n={1}
              title="Install Ollama"
              body={
                <>
                  Download and run the installer from{" "}
                  <a
                    href={OLLAMA_URL}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-amber-400 hover:text-amber-300 underline-offset-2 hover:underline"
                  >
                    ollama.com/download
                  </a>
                  . After install it runs in the background and exposes a
                  local API on{" "}
                  <code className="text-amber-400 font-mono text-xs bg-amber-500/8 px-1.5 py-0.5 rounded">
                    http://localhost:11434
                  </code>
                  .
                </>
              }
            />
            <Step
              n={2}
              title="Pull the AI model"
              body={
                <>
                  Open PowerShell and run this once. It downloads the small
                  model FPSOpti AI uses (~ a few hundred MB).
                </>
              }
              code="ollama pull qwen3:0.6b"
            />
            <Step
              n={3}
              title="Run FPSOpti AI"
              body={
                <>
                  Double-click <span className="font-mono">FPSOptiAI.exe</span>.
                  No Python or extra setup required. The first launch can take
                  a couple of seconds while the bundled assets unpack.
                </>
              }
            />
          </div>
        </div>
      </section>

      {/* How to use */}
      <section className="border-t border-[#27272a]/70 bg-[#0a0a0a]">
        <div className="max-w-5xl mx-auto px-6 py-16">
          <h2 className="text-2xl font-bold tracking-tight mb-8">
            How to use it
          </h2>
          <ol className="space-y-4">
            {[
              "Click Scan My PC. Your hardware fills in the Detected Specs card.",
              "Optionally edit any spec the scanner got wrong (CPU, GPU, RAM, resolution).",
              "Fill in the game form: name, target FPS, in-game resolution, priority (Max FPS / Balanced / Best Quality / Competitive), and any notes.",
              "Click Generate Optimization Plan. The AI report streams in live.",
              "Click Export as .txt to save the report.",
            ].map((line, i) => (
              <li key={i} className="flex gap-4">
                <span className="flex-none w-7 h-7 rounded-md bg-amber-500/10 border border-amber-500/30 text-amber-400 text-xs font-mono font-semibold flex items-center justify-center">
                  {i + 1}
                </span>
                <p className="text-[#a1a1aa] text-sm leading-relaxed pt-0.5">
                  {line}
                </p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* Privacy */}
      <section className="border-t border-[#27272a]/70 bg-[#0a0a0a]">
        <div className="max-w-5xl mx-auto px-6 py-16">
          <div className="flex items-start gap-4 bg-[#18181b] border border-[#27272a] rounded-xl p-6">
            <Lock
              size={20}
              className="text-amber-400 mt-0.5 shrink-0"
              aria-hidden
            />
            <div>
              <h3 className="text-[#e4e4e7] font-semibold mb-2">
                100% local — no data leaves your PC
              </h3>
              <p className="text-[#a1a1aa] text-sm leading-relaxed">
                Hardware scans run on-device. The AI recommendation is
                generated by a model running locally through Ollama, so your
                specs, game info, and notes are never uploaded anywhere.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Troubleshooting */}
      <section className="border-t border-[#27272a]/70 bg-[#0a0a0a]">
        <div className="max-w-5xl mx-auto px-6 py-16">
          <h2 className="text-2xl font-bold tracking-tight mb-8">
            Troubleshooting
          </h2>
          <div className="space-y-5">
            <Troubleshoot
              q='"Ollama does not seem to be running."'
              a={
                <>
                  Open the Ollama app, or run{" "}
                  <code className="text-amber-400 font-mono text-xs bg-amber-500/8 px-1.5 py-0.5 rounded">
                    ollama run qwen3:0.6b
                  </code>{" "}
                  in PowerShell, then click Generate again.
                </>
              }
            />
            <Troubleshoot
              q={'"The model ‘qwen3:0.6b’ is not installed."'}
              a={
                <>
                  Run{" "}
                  <code className="text-amber-400 font-mono text-xs bg-amber-500/8 px-1.5 py-0.5 rounded">
                    ollama pull qwen3:0.6b
                  </code>{" "}
                  in PowerShell.
                </>
              }
            />
            <Troubleshoot
              q="Generation is slow on the first run"
              a="The first request loads the model into memory. Subsequent requests stream much faster."
            />
            <Troubleshoot
              q='Some specs show as "Unknown"'
              a="Older Windows installs or virtualized GPUs don't always expose VRAM or driver version. Use the manual override fields under Detected Specs to fill them in."
            />
            <Troubleshoot
              q="Windows SmartScreen warning on first launch"
              a={
                <>
                  Single-file PyInstaller builds occasionally trigger a
                  SmartScreen prompt because the .exe isn't code-signed. Click{" "}
                  <span className="font-mono text-xs">More info</span> →{" "}
                  <span className="font-mono text-xs">Run anyway</span> if
                  you trust the source (this repo).
                </>
              }
            />
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t border-[#27272a]/70 bg-[#0a0a0a]">
        <div className="max-w-5xl mx-auto px-6 py-20 text-center">
          <Gauge size={28} className="text-amber-400 mx-auto mb-5" />
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight mb-4">
            Ready to tune your settings?
          </h2>
          <p className="text-[#a1a1aa] text-sm leading-relaxed max-w-[520px] mx-auto mb-8">
            Grab the latest build and run it locally. Source is on GitHub if
            you want to inspect or modify it.
          </p>
          <div className="flex flex-wrap justify-center gap-3">
            <a
              href={DOWNLOAD_URL}
              download
              className="inline-flex items-center gap-2 px-5 py-3 bg-amber-600 hover:bg-amber-500 text-white text-sm font-medium rounded-lg transition-all duration-200 hover:shadow-lg hover:shadow-amber-500/20"
            >
              <Download size={16} />
              Download FPSOptiAI.exe
            </a>
            <a
              href={REPO_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-5 py-3 border border-[#27272a] hover:border-amber-500/50 text-[#a1a1aa] hover:text-[#e4e4e7] text-sm font-medium rounded-lg transition-all duration-200"
            >
              <GitHubIcon size={16} />
              View source
            </a>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-[#27272a]/70 py-8 bg-[#0a0a0a]">
        <div className="max-w-5xl mx-auto px-6 text-center text-[#52525b] text-sm">
          Martin Gonzalez © 2026. All rights reserved.
        </div>
      </footer>
    </main>
  );
}

function FeatureCard({
  icon,
  title,
  body,
}: {
  icon: React.ReactNode;
  title: string;
  body: string;
}) {
  return (
    <div className="bg-[#18181b] border border-[#27272a] rounded-xl p-5 hover:border-amber-500/40 transition-colors duration-300">
      <div className="w-9 h-9 rounded-md bg-amber-500/10 border border-amber-500/30 text-amber-400 flex items-center justify-center mb-4">
        {icon}
      </div>
      <h3 className="text-[#e4e4e7] font-semibold text-sm mb-2">{title}</h3>
      <p className="text-[#71717a] text-sm leading-relaxed">{body}</p>
    </div>
  );
}

function Step({
  n,
  title,
  body,
  code,
}: {
  n: number;
  title: string;
  body: React.ReactNode;
  code?: string;
}) {
  return (
    <div className="bg-[#18181b] border border-[#27272a] rounded-xl p-5 sm:p-6">
      <div className="flex items-center gap-3 mb-3">
        <span className="w-7 h-7 rounded-md bg-amber-500/10 border border-amber-500/30 text-amber-400 text-xs font-mono font-semibold flex items-center justify-center">
          {n}
        </span>
        <h3 className="text-[#e4e4e7] font-semibold text-base">{title}</h3>
      </div>
      <p className="text-[#a1a1aa] text-sm leading-relaxed">{body}</p>
      {code && (
        <div className="mt-4 flex items-center gap-2 bg-[#0a0a0a] border border-[#27272a] rounded-lg px-3 py-2.5">
          <Terminal size={14} className="text-amber-400 shrink-0" />
          <code className="text-[#e4e4e7] font-mono text-xs sm:text-sm break-all">
            {code}
          </code>
        </div>
      )}
    </div>
  );
}

function Troubleshoot({
  q,
  a,
}: {
  q: string;
  a: React.ReactNode;
}) {
  return (
    <div className="bg-[#18181b] border border-[#27272a] rounded-xl p-5">
      <p className="text-[#e4e4e7] font-semibold text-sm mb-2">{q}</p>
      <p className="text-[#a1a1aa] text-sm leading-relaxed">{a}</p>
    </div>
  );
}
